# Generated by Django 4.2 on 2023-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_recipe_recette_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='count',
            field=models.IntegerField(default=0, max_length=500),
        ),
    ]
