# Generated by Django 4.2 on 2023-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_recipe_image_alter_ingredient_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='../static/unknown.png', upload_to='recettes/'),
        ),
    ]
